### ISSUE TITLE
How to show/display CondensedAttribution control (Branded - Open mode)

### ISSUE THREAD

**Issue by abrobia** [route360/Leaflet.CondensedAttribution#1]
hello, while trying to implement this plugin, I am looking for the syntax which allows the condensed attribution control (Branded - Open mode) to be always showed/displayed on the map. 

Any suggestions about how to overwrite the CSS / how to add control options to reach this goal?

thank you in advance

**Comment by StefanBrand** [comment]
If you have a look at the [CSS](https://github.com/route360/Leaflet.CondensedAttribution/blob/master/dist/leaflet-control-condended-attribution.css) you can see these attributes:

```css
.leaflet-condensed-attribution .attributes-body {
  display: none;
  /*...*/
}

.leaflet-condensed-attribution:hover .attributes-body {
  display: inline-block !important;
}
```

You can simply set `display: none` to `display: inline-block !important`.

____

Using Javascript you could add this to your code:
```js
document.querySelector('.leaflet-condensed-attribution .attributes-body').style.display = 'inline-block !important'
```
